version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: Go "
    reviewers:
      - "stepanstipl"
      - "dark0dave"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
    commit-message:
      prefix: "dep: Docker "
    reviewers:
      - "stepanstipl"
      - "dark0dave"
