name: main
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
env:
  KAFKA_VERSION: 3.4.1
  SCALA_VERSION: 2.13
  IMAGE_NAME: ${{ github.repository }}
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        set-safe-directory: true
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          platforms: |
            linux/arm64
            linux/amd64
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            KAFKA_VERSION=${{ env.KAFKA_VERSION }}
            SCALA_VERSION=${{ env.SCALA_VERSION }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
  push-image:
    name: Push Image
    needs:
      [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: dark0dave
          password: ${{ secrets.DOCKERHUBTOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms:  |
            linux/amd64
            linux/arm64
          tags: |
            ${{ format('docker.io/dark0dave/kafka:{0}-{1}', env.KAFKA_VERSION, env.SCALA_VERSION) }}
            ${{ ( !startsWith(github.ref, 'refs/tags/nightly') && format('docker.io/dark0dave/kafka:{0}', 'latest') ) || '' }}
            ${{ format('ghcr.io/{0}:{1}-{2}', env.IMAGE_NAME, env.KAFKA_VERSION, env.SCALA_VERSION) }}
            ${{ ( !startsWith(github.ref, 'refs/tags/nightly') && format('ghcr.io/{0}:{1}', env.IMAGE_NAME, 'latest') ) || '' }}
          build-args: |
            KAFKA_VERSION=${{ env.KAFKA_VERSION }}
            SCALA_VERSION=${{ env.SCALA_VERSION }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
